### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by afardel** [jkandzi/Progress.swift#7]
Could there be a support for Swift 5?

Currently, if you have another SPM with depends on Progress, on `swift build` command, you'll get:

```
$>swift build
[MyPersonalProjectPath]/.build/checkouts/Progress.swift: error: package at '[MyPersonalProjectPath]/.build/checkouts/Progress.swift' is using Swift tools version 3.1.0 which is no longer supported; use 4.0.0 or newer instead
```

We can do `swift package tools-version --set-current` on the Progress folder, which will change in *Package.swift*:
```
// swift-tools-version:4.0
```
to:
```
// swift-tools-version:5.0
```

This can later be tested if you've cloned the Progress repository, then updated the swift-tools-version, and use:
```
.package(path: "../[MyLocalPathToProgressWithSwiftToolVersionUpdate]/")
```
instead of:

```
.package(url: "https://github.com/jkandzi/Progress.swift.git", from: "0.3.0")
```

While waiting for a 0.4.0 version.

**Comment by brodney** [comment]
This migration happened in #6 but we need a tag to reference in swift pm. @jkandzi can you add this please?

**Comment by jkandzi** [comment]
The error message says `use 4.0.0 or newer instead` #6 added `// swift-tools-version:4.0` to *Package.swift*. I just added a tag for version 0.4.0.

Does this fix your issue?

**Comment by afardel** [comment]
My bad, I didn't saw that the #6 was fixing it but no tag have been generated.

Works perfectly now with `0.4.0` tag ;)
